- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
Adding CODE_OF_CONDUCT, CONTRIBUTING, more README, etc.
> Adding repo housekeeping

- deepgram.go
- invitations.go
- transcriptions.go
- usage.go
Fixes broken compilation and allows `go test ./...` to pass
> fix: syntax error (missing bracket)

- README.md
The added installation guide in the readme. 
- Install the repo and dependencies for the sdk
- Run the example 
Addressing #7
> added installation instructions in readme

- deepgram/deepgram.go
- deepgram/prerecorded.go
- deepgram/transcriptions.go
- examples/preRecordedFromUrl_example.go
Added `ToWebVTT` and `ToSRT` functions in order to more easily provide transcription files for users after the audio is transcribed. Both functions receive `PreRecordedResponse`.
> Adding to srt and web vtt

- deepgram/billing.go
- deepgram/deepgram.go
- deepgram/invitations.go
- deepgram/keys.go
- deepgram/members.go
- deepgram/projects.go
- deepgram/transcriptions.go
- deepgram/usage.go
- go.mod
Added in missing endpoints. 
- Keys
- Projects
- Members
- Usage
- Billing
Add Summarize, DetectLanguage, DetectTopics to PrerecordedTranscriptionOptions
> Feature parity

- deepgram/prerecorded.go
Add Entity and Topic Detection Types.
> Add Entity and Topic Detection Types

- examples/liveTranscription_example.go
- examples/preRecordedFromStream_example.go
- examples/preRecordedFromUrl_example.go
- go.mod
Unable to install pacakage with the name `github.com/deepgram-devs/deepgram-go-sdk`, the package is internally named as `go-sdk` instead of `ddepgram-go-sdk` as per the github repository.
Let me know if this change is valid. Or any other alternatives are considered.
> Fix package name

- .github/PULL_REQUEST_TEMPLATE.md
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
> change name to Go SDK

- examples/liveTranscription_example.go
Fix the broken link in examples/liveTranscription_example.go
- [ x] Documentation update or tests (if none of the other choices apply)
- [x ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
> fix livestream link in example/liveTranscription

- deepgram/prerecorded.go
- go.mod
- go.sum
Update the fields in PreRecordedResponse to make sure responses are unmarshalled correctly
- [x ] Bugfix (non-breaking change which fixes an issue)
> update response structure

- deepgram/prerecorded.go
Add ParagraphGroup and related structs to correctly decode json responses 
- [ x] Bugfix (non-breaking change which fixes an issue)
- [ x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
> Fix paragraph not showing in results

- deepgram/prerecorded.go
Update speaker field in Utterance to fix extraneous `speaker: 0` when diarize is not turned on
- [ x] Bugfix (non-breaking change which fixes an issue)
> Fix extraneous speaker field in utterance

- deepgram/prerecorded.go
Add smart format option to PreRecordedTranscriptionOptions
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
> Add smart format

- README.md
Readme update to match other SDKs readme format
> Readme update to match other SDKs readme format

- .github/workflows/go.yml
- deepgram/prerecorded.go
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
> adds gh action

- deepgram/prerecorded.go
Add support for sentiment analysis, related issue: https://github.com/deepgram-devs/deepgram-go-sdk/issues/16
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
> add support for sentiment analysis

- deepgram/prerecorded.go
Add warnings array in the metadata struct in response, add result in the summaryV2 struct 
- [ x] New feature (non-breaking change which adds functionality)
> add warnings in metadata and result in summary v2

- .github/workflows/go.yml
Changing to the command `go test -v ./tests` in github action so that tests run
> fix test command

- deepgram/deepgram.go
I'm manually updating the `sdkVersion` to 0.10.0, which will be the tag we use for the release that I am about to do.
> manually updates sdkVersion before release

- deepgram/prerecorded.go
- deepgram/transcriptions.go
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
> feat: filler words release

- deepgram/billing.go
- deepgram/invitations.go
- deepgram/keys.go
- deepgram/members.go
- deepgram/prerecorded.go
- deepgram/projects.go
- deepgram/transcriptions.go
- deepgram/usage.go
- examples/liveTranscription_example.go
- examples/preRecordedFromStream_example.go
- examples/preRecordedFromUrl_example.go
Resolves: https://github.com/deepgram-devs/deepgram-go-sdk/issues/71
log.Fatal(err), is causing our workers to crash since that is an OS exit 
> Replace log.Fatal with log.Panic to avoid crashing the application

- deepgram/transcriptions.go
Avoid referencing pointers that might not exist.
> Fix: potential nil pointer dereference + return error

- README.md
- docs.go
- examples/README.md
- examples/prerecorded/main.go
- examples/projects/main.go
- examples/streaming/main.go
- go.mod
- go.sum
- pkg/api/manage/v1/billing.go
- pkg/api/manage/v1/invitations.go
- pkg/api/manage/v1/keys.go
- pkg/api/manage/v1/manage.go
- pkg/api/manage/v1/members.go
- pkg/api/manage/v1/projects.go
- pkg/api/manage/v1/types.go
- pkg/api/manage/v1/usage.go
- pkg/api/prerecorded/v1/prerecorded.go
- pkg/api/prerecorded/v1/types.go
- pkg/client/live/client.go
- pkg/client/prerecorded/client.go
- tests/prerecorded_test.go
Addresses https://github.com/deepgram-devs/deepgram-go-sdk/issues/91. This restructures the project according to typical `go` conventions.
This implements the following:
- Observe `go` conventions by placing packages into the `pkg` folder and break down modules by functionality
- Moves client structs into `pkg/client`
- Prerecorded Client (REST based) has moved to `pkg/client/prerecorded`
- Live Client (Websocket-based) has moved to `pkg/client/live`
- Moves all the management functionality into `pkg/api/manage`. These are functions like ListProjects, etc.
- Prerecorded and Live examples located at `examples/prerecorded` and `examples/streaming` work as before
- A new `examples/projects` was added to verify the move of the `manage` REST calls to `pkg/api/manage`. This implements an …
> Restructure SDK Based on Go Project Conventions

- docs.go
- examples/prerecorded/main.go
- examples/projects/main.go
- examples/streaming/main.go
- pkg/api/manage/v1/billing.go
- pkg/api/manage/v1/invitations.go
- pkg/api/manage/v1/keys.go
- pkg/api/manage/v1/manage.go
- pkg/api/manage/v1/members.go
- pkg/api/manage/v1/projects.go
- pkg/api/manage/v1/types.go
- pkg/api/manage/v1/usage.go
- pkg/api/prerecorded/v1/prerecorded.go
- pkg/api/prerecorded/v1/types.go
- pkg/client/live/client.go
- pkg/client/prerecorded/client.go
- tests/mocks.go
- tests/prerecorded_test.go
**NOTE:** This depends on https://github.com/deepgram-devs/deepgram-go-sdk/pull/86 and is targeted to `go-sdk-v1` release. Will rebase when https://github.com/deepgram-devs/deepgram-go-sdk/pull/86 is merged. Until it gets merged, here is a better looking diff to track the changes between branches: https://github.com/dvonthenen/deepgram-go-sdk/compare/restructure-project-using-go-conventions...dvonthenen:deepgram-go-sdk:dv/update-headers-with-licensing
Addresses https://github.com/deepgram-devs/deepgram-go-sdk/issues/90. This adds a Copyright header to all source files using the MIT license as described in the `LICENSE` file at the root of the repo.
_Put an `x` in the boxes that …
> Update All Source Code Files With Licensing

- pkg/api/version/live-version.go
- pkg/client/interfaces/types-stream.go
- pkg/client/live/client.go
- pkg/client/live/types.go
- pkg/common/constants.go
This handles a refactor of the Live/Stream client after taking into account changes in the HTTP/REST changes for the `Manage API` changes. This is just to give a consistent look-and-feel for changes coming to HTTP/REST plumbing.
Changes include:
- fixes `examples/streaming` with the new ClientOptions on the Live Client
- changes to `version. GetLiveAPI ` which allows defaults and overrides for the URL for the prerecorded endpoint
NA
> Implements the Live/Streaming Refactor for Upcoming REST/HTTP `Manage API` Client Changes

- examples/invitations/main.go
- examples/keys/main.go
- examples/members/main.go
- examples/projects/main.go
- examples/scopes/main.go
- examples/usage/main.go
Depends on PR https://github.com/deepgram-devs/deepgram-go-sdk/pull/108, https://github.com/deepgram-devs/deepgram-go-sdk/pull/109, and https://github.com/deepgram-devs/deepgram-go-sdk/pull/110
Here is a clean diff between the dependent branch:
https://github.com/dvonthenen/deepgram-go-sdk/compare/dv/refactor-manage-minimal-diff...dvonthenen:deepgram-go-sdk:dv/manage-api-examples
Implements examples for every single API call within the `Manage API`:
- `examples/balances`
- `examples/invitations`
- `examples/keys`
- `examples/members`
- `examples/projects`
- `examples/scopes`
- `examples/usage`
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. …
> Provide Examples for All `Manage API` Calls

- examples/prerecorded/file/main.go
- pkg/client/prerecorded/client.go
Addresses Issue: https://github.com/deepgram-devs/deepgram-go-sdk/issues/125
Can be verified with `examples/prerecorded/file`.
> Fix upload file to `/listen`

- pkg/client/interfaces/types-prerecorded.go
Remove Legacy/Deprecated PreRecorded Option/Param
NA
> Remove Legacy/Deprecated PreRecorded Option/Param

- pkg/client/interfaces/types-prerecorded.go
- pkg/client/interfaces/types-stream.go
Remove All Deprecated Options for Live/PreRecorded Transcriptions
NA
> Remove All Deprecated Options for Live/PreRecorded Transcriptions

- README.md
This updates the README for the v1 release. This should be way simpler than before. The other version was very chatty.
> Update the README.md for v1

- examples/streaming/http/main.go
- examples/streaming/microphone/main.go
- examples/streaming/replay/main.go
- pkg/client/live/client.go
live.Stop() keeps retrying even when you really want it to Stop().
> On ws.Stop() Turn Retry=False to Stop Reconnecting

- README.md
Sync README with Python SDK
NA
> Updates to README to Sync with Python SDK

- examples/manage/balances/main.go
- examples/manage/invitations/main.go
- examples/manage/keys/main.go
- examples/manage/members/main.go
- examples/manage/projects/main.go
- examples/manage/scopes/main.go
- examples/manage/usage/main.go
- examples/prerecorded/callback/callback/main.go
- examples/prerecorded/file/main.go
- examples/prerecorded/stream/main.go
- examples/prerecorded/url/main.go
This is just to enhance readability
Checked the examples to make sure they all work.
> Use `fmt` Instead of `log` for Examples

- pkg/api/live/v1/interfaces/types.go
Missing Speaker Index on Live Stream
> Missing Speaker Index on Live Stream

- pkg/api/prerecorded/v1/interfaces/types.go
After doing an audit between the SDKs (JS, Go, Python), these were the inconsistencies that I found for Go.
- `language_confidence` in Prerecorded->..->Channel
- `Translation` in Prercorded->Alternative
```
class Translation:
language: Optional[str] = ""
translation: Optional[str] = ""
```
`sentiment` is not yet implement. This is work to be released.
Tested all examples and everything works fine!
If this is a relatively large or …
> Fix Missing Values After Audit

- examples/manage/usage/main.go
- pkg/api/manage/v1/interfaces/types.go
- pkg/client/rest/rest.go
Implements Manage Tokens for SITS. Altered the example to just dump the entire JSON object instead of iterating over specific fields in the object.
Addresses issue: https://github.com/deepgram/deepgram-go-sdk/issues/115
Other changes to support this PR:
- Modified REST client so that we can dump the raw JSON before marshalling: pkg/client/rest/rest.go. This helps with debugging. 
- Added some missing omitempty and URL fields which shouldn't matter, but more of a just in case.
Tested functionality using `examples/manage/usage` and everything appears to function properly.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …
> Implements Manage Tokens for SITS

- pkg/api/live/v1/interfaces/types.go
Updates the UtteranceEnd Message with latest changes.
```
{"type":"UtteranceEnd","channel":[0,2],"last_word_end":1.175}
```
NA
> Update UtteranceEnd Message With Latest

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This updates the Issue and PR templates to put the instructions in hidden comments that only the users sees when opening an Issue/PR, but that won't be visible when posting if not deleted.
This also updates the COC and Contrib Guide formatting for markdown linting.
NA
> Update Issue and PR Templates, Update Various Guides Formatting to Match Python

- examples/prerecorded/file/main.go
- pkg/api/live/v1/interfaces/types.go
- pkg/api/live/v1/router.go
- pkg/client/interfaces/types-prerecorded.go
- pkg/client/interfaces/types-stream.go
Updates Extras Parameter for Live Streaming. I was double checking things an noticed that the Options parameters needed to be changes from string -> []string and the Extra field seems to also exist on the Metadata object on the Live TranscriptionMessage
Tested on `examples/streaming/microphone`.
> Extras Parameter for Live Streaming, Options Fix

- pkg/client/interfaces/types-prerecorded.go
Fix Custom Intent to be []string
NA
> Fix Prerecorded Options for Custom Intent

- pkg/client/live/client.go
The KeepAlive message is being sent as Binary (aka Microphone) data when it should be sent as Text (aka a Control) message.
> Fix KeepAlive Message as Text

- pkg/client/interfaces/options.go
Not really a big deal yet since the flag isn't being used.
NA
> OnPrem Error Logic Error

- pkg/client/interfaces/options.go
Addresses issue: https://github.com/deepgram/deepgram-go-sdk/issues/182
NA
> Fix API Key Ordering Precedence

- pkg/client/interfaces/types-prerecorded.go
- pkg/client/interfaces/types-stream.go
Addresses Issue: https://github.com/deepgram/deepgram-go-sdk/issues/183
NA
> Add Numerals formatting feature

- pkg/client/interfaces/utils.go
> Bump Go Version in Agent String

- pkg/api/prerecorded/v1/interfaces/types.go
Missing `speaker` Field in `Paragraph`
NA
> Missing `speaker` Field in `Paragraph`

- pkg/client/interfaces/types-prerecorded.go
> added query parameters for pre-recorded G.729 audio

- README.md
Information on setting Logging for Python SDK. This matches the documentation currently available in .NET.
NA
> Update README with Logging Info/Settings, Move Go Docs Into Docs Section

- pkg/api/manage/v1/interfaces/types.go
Missing `Key` value in Response.
NA
> Update KeyResponse with Key Value

- pkg/api/manage/v1/interfaces/types.go
- pkg/api/manage/v1/keys.go
Fix issue: https://github.com/deepgram/deepgram-go-sdk/issues/205
NA
> Fix CreateKey TTL Property

- pkg/client/interfaces/types-stream.go
Implements https://github.com/deepgram/deepgram-go-sdk/issues/204
NA
> Implement `no_delay`

- examples/prerecorded/file/main.go
- examples/prerecorded/url/main.go
- pkg/api/analyze/v1/interfaces/types.go
- pkg/api/manage/v1/interfaces/types.go
- pkg/api/prerecorded/v1/interfaces/types.go
- pkg/api/speak/v1/interfaces/types.go
- pkg/client/common/common.go
- pkg/client/interfaces/utils.go
Addresses: https://github.com/deepgram/deepgram-go-sdk/issues/218
NA
> Fix `DeepgramError` Not Getting Returned as Error Type

- .github/workflows/tests-daily.yaml
- .github/workflows/tests-unit.yaml
- pkg/api/live/v1/interfaces/constants.go
- pkg/api/live/v1/interfaces/types.go
- pkg/client/live/client.go
- pkg/client/live/constants.go
Implements https://github.com/deepgram/deepgram-go-sdk/issues/197
NA
> Implements `Finalize` Message

- examples/prerecorded/file/main.go
- examples/streaming/microphone/main.go
- examples/streaming/test/main.go
- pkg/api/live/v1/default.go
- pkg/api/live/v1/router.go
- pkg/client/interfaces/types-client.go
- pkg/client/live/client.go
- pkg/client/live/constants.go
- pkg/client/live/types.go
- pkg/client/prerecorded/client.go
Addresses: https://github.com/deepgram/deepgram-go-sdk/issues/220
This change does the following:
- Fixes fatal closure of the websocket
- Allows the user to pass in their own cancel function
- Fixes open/close messages to be 1-to-1
- Fixes Deepgram Error messages to be passed to callback
- Updated examples with better guidance on handling these fatal errors
- Updated default/demo callback struct for easier debugging
NA
> Fix Reconnect Issue

- pkg/client/interfaces/options.go
- pkg/client/interfaces/types-client.go
- pkg/common/interfaces.go
Addresses: https://github.com/deepgram/deepgram-go-sdk/issues/221
This isn't really a breaking change because self hosted (aka OnPrem) isn't implemented in this SDK yet. Tracking issue: https://github.com/deepgram/deepgram-go-sdk/issues/224
> Update OnPrem References to Self Hosting

- tests/edge_cases/cancel/main.go
Implements an example of cancelling a Live Client connection.
NA
> Example Cancel on Live Client

- pkg/client/interfaces/types-stream.go
> Added support for tier to ensure backward compatibility

- pkg/client/interfaces/v1/types-agent.go
> feat: support context length option

- .github/CODEOWNERS
Adds DX code owners for PR review notification purposes.
> chore: adds dx code owners
