deepgram/deepgram-go-sdk

- deepgram/transcriptions.go
Solves: https://github.com/deepgram-devs/deepgram-go-sdk/issues/27
Timestamps under 10 seconds render as: `00:00:1.814`, and should be `00:00:01.814` according to the [WebVTT Spec](https://www.w3.org/TR/webvtt1/#webvtt-timestamp):
> 4. Two [ASCII digits](https://www.w3.org/TR/html51/infrastructure.html#ascii-digits), representing the seconds as a base ten integer in the range 0 ≤ seconds ≤ 59.
Go's float formatting requires you specify the _total_ number of digits as the first number (including the decimal point) and the decimal precision as the second number:
```
return fmt.Sprintf("%02d:%02d:%02.3f", hours, minutes, seconds)
```
Should be:
```
return fmt.Sprintf("%02d:%02d:%06.3f", hours, minutes, seconds)
```
_Put an `x` in the boxes that apply. You can also fill these out after …
> Fix padding on SecondsToTimestamp

- README.md
The instruction `go get https://github.com/deepgram-devs/deepgram-go-sdk` is incorrect. Because `http://` is not allowed as a go mod link.
> fix the install instructions in readme

- deepgram/prerecorded.go
Change `Utt_split` data type to **float64** so it can accept decimals. Right now it is **int**, so it only accepts whole numbers.
> change int to float64

- go.mod
- go.sum
- tests/mocks.go
- tests/prerecorded_test.go
Add simple unit tests for prerecorded.go. Introduce dependency on httpmock(https://pkg.go.dev/github.com/jarcoal/httpmock)
- [ x] Documentation update or tests (if none of the other choices apply)
- [x ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ x] Lint and unit tests pass locally with my changes
- [ x] I have added tests that prove my fix is effective or that my feature works
If this is a relatively large or complex …
> Add tests for PreRecorded

- deepgram/transcriptions.go
Defined in https://developers.deepgram.com/reference/streaming but not yet included in the streaming API request.
> Add 'smart_format' to LiveTranscriptionOptions

- deepgram/deepgram.go
- deepgram/prerecorded.go
Add `TranscriptionPath` to deepgram client which allows user to specify path to different endpoints
Currently we have not fully supported features on sandbox
> add support for change of path

- README.md
- Add discord badge to the top of the README (Resolves #82 )
Tested on
- local build
Results:
> chore: Add discord badge in readme.md 

- examples/streaming/main.go
- go.mod
- go.sum
- pkg/api/live/v1/constants.go
- pkg/api/live/v1/default.go
- pkg/api/live/v1/interfaces/constants.go
- pkg/api/live/v1/interfaces/interfaces.go
- pkg/api/live/v1/interfaces/types.go
- pkg/api/live/v1/router.go
- pkg/api/live/v1/types.go
- pkg/client/interfaces/constants.go
- pkg/client/interfaces/types-stream.go
- pkg/client/interfaces/utils.go
- pkg/client/live/client.go
- pkg/client/live/constants.go
- pkg/client/live/types.go
**NOTE:** This depends on https://github.com/deepgram-devs/deepgram-go-sdk/pull/86 and https://github.com/deepgram-devs/deepgram-go-sdk/pull/87 and is targeted to `go-sdk-v1` release. Will rebase when https://github.com/deepgram-devs/deepgram-go-sdk/pull/86 and https://github.com/deepgram-devs/deepgram-go-sdk/pull/87 are merged. The diff in this PR will look pretty nasty until subsequent depend PRs are merged first. Until these get merged, here is a better looking diff to track the changes between branches: https://github.com/dvonthenen/deepgram-go-sdk/compare/dv/update-headers-with-licensing...dvonthenen:deepgram-go-sdk:dv/live-streaming-object-definition
Addresses https://github.com/deepgram-devs/deepgram-go-sdk/issues/89 and https://github.com/deepgram-devs/deepgram-go-sdk/issues/35. …
> Encapsulate the Live/Stream Object to Hide Internal Details

- examples/prerecorded/main.go
- pkg/api/version/prerecorded-version.go
- pkg/client/interfaces/types-prerecorded.go
- pkg/client/live/client.go
- pkg/client/prerecorded/client.go
- pkg/client/prerecorded/types.go
- pkg/client/rest/rest.go
- pkg/client/rest/types.go
- tests/prerecorded_test.go
Depends on PR https://github.com/deepgram-devs/deepgram-go-sdk/pull/108
Here is a clean diff between the dependent branch:
https://github.com/dvonthenen/deepgram-go-sdk/compare/dv/refactor-rest-client...dvonthenen:deepgram-go-sdk:dv/refactor-rest-prerecorded-client
This handles a refactor of the Prerecorded client after taking into account changes in the HTTP/REST changes for the `Manage API` changes. This is just to give a consistent look-and-feel for changes coming to HTTP/REST plumbing.
Changes include:
- fixes `examples/prerecorded` with the new ClientOptions on the Prerecorded Client
- changes to `version.GetPrerecordedAPI` which allows defaults and overrides for the URL for the prerecorded endpoint
_Put an `x` …
> Implements the Prerecorded Refactor for Upcoming REST/HTTP `Manage API` Client Changes

- examples/prerecorded/callback/README.md
Include a README for the [callback example](https://github.com/deepgram-devs/deepgram-go-sdk/tree/main/examples/prerecorded/callback).
> Callback Example README

- examples/prerecorded/url/main.go
- examples/streaming/microphone/main.go
- examples/streaming/replay/main.go
- pkg/client/interfaces/types-prerecorded.go
- pkg/client/interfaces/types-stream.go
- tests/prerecorded_test.go
This fixes more linting issues with struct variable names. This will throw errors on strict linting with Go.
Verified that all prerecord and live examples still work correctly.
NA
> Fix More Go Lint Issues With Struct Names

- examples/streaming/microphone/main.go
- pkg/api/live/v1/default.go
- pkg/api/live/v1/interfaces/interfaces.go
- pkg/api/live/v1/interfaces/types.go
- pkg/api/live/v1/router.go
- pkg/api/manage/v1/interfaces/types.go
- pkg/client/live/client.go
- pkg/client/live/constants.go
- pkg/client/live/types.go
This PR contains the following changes:
- The WS protocol should ping every 20 seconds
- The Deepgram protocol should ping with [KeepAlive every 5 seconds](https://developers.deepgram.com/reference/streaming#stream-keepalive)
- Exposes the `Error` Callback in the Live interface as it might be useful for recovery scenarios
- Consistency for singular versus plural where it makes sense in the struct names
- KeepAlive messages are disabled by default but can be optionally enabled.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …
> Fix KeepAlive Interval and Expose Error Callback

- pkg/api/live/v1/default.go
- pkg/audio/microphone/microphone.go
- pkg/audio/replay/replay.go
- pkg/client/live/client.go
- pkg/client/rest/debug.go
- pkg/client/rest/debug/file.go
- pkg/common/init.go
- tests/prerecorded_test.go
Running [golangci-lint](https://github.com/golangci/golangci-lint) locally gave the following issues:
```
vonthd@vonthds-MacBook-Pro-2:deepgram-go-sdk$ ./golangci-lint run -v --timeout=5m
INFO [config_reader] Config search paths: [./ /Users/vonthd/go/src/github.com/deepgram/deepgram-go-sdk /Users/vonthd/go/src/github.com/deepgram /Users/vonthd/go/src/github.com /Users/vonthd/go/src /Users/vonthd/go /Users/vonthd /Users /] 
INFO [lintersdb] Active 6 linters: [errcheck gosimple govet ineffassign staticcheck unused] 
INFO [loader] Go packages loading at mode 575 (name|files|deps|exports_file|imports|types_sizes|compiled_files) took 2.427023375s 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 4.248833ms 
INFO [linters_context/goanalysis] analyzers took 3.777163166s with top 10 …
```
> Updates for Go Lint Using golangci-lint

- examples/manage/invitations/main.go
- examples/manage/members/main.go
- examples/manage/scopes/main.go
- examples/prerecorded/file/main.go
- examples/prerecorded/stream/main.go
- examples/prerecorded/url/main.go
- examples/streaming/microphone/main.go
- examples/streaming/replay/main.go
This just fixes some comments in the examples.
NA
> Fix Example Comments

- pkg/api/live/v1/default.go
- pkg/api/live/v1/interfaces/constants.go
- pkg/api/live/v1/interfaces/interfaces.go
- pkg/api/live/v1/interfaces/types.go
- pkg/api/live/v1/router.go
Reference: https://github.com/deepgram/deepgram-go-sdk/issues/146
> Add TypeUtteranceEndResponse & handle case in live.router

- examples/prerecorded/file/main.go
This is an example on sending a custom query parameter and a custom header for a given REST API call. Since these are custom, by definition there is zero error checking that happens.
```
// example on how to send a custom header
headers := make(map[string][]string, 0)
headers["MY-CUSTOM-HEADER"] = []string{"CUSTOM"}
ctx = cfginterfaces.WithCustomHeaders(ctx, headers)
// example on how to send a custom parameter
params := make(map[string][]string, 0)
params["utterances"] = []string{"true"}
ctx = cfginterfaces.WithCustomParameters(ctx, params)
```
If you enable verbose debugging, this is what it looks like then under the covers:
```
I1214 06:41:45.807373    4217 client.go:131] Connecting to https://api.deepgram.com/v1/listen?diarize=true&language=en-US&punctuate=true&utterances=true
I1214 …
```
> Example on Sending Custom Param/Header

- examples/streaming/http/main.go
- examples/streaming/microphone/main.go
- pkg/api/live/v1/default.go
- pkg/api/live/v1/router.go
- pkg/client/interfaces/types-stream.go
- pkg/client/interfaces/utils.go
This adds onto the https://github.com/deepgram/deepgram-go-sdk/pull/147 PR.
Changes include:
- Exposing the `UtteranceEndMs ` variable to set the feature
- Changed some of the trace messages so they aren't so chatty when debugging this feature
- Adds onto the `Use fmt Instead of log for Examples` PR https://github.com/deepgram/deepgram-go-sdk/pull/148
Tested all examples to make sure they work!
> Update Utterance Feature (Expose Variable, Logging, etc)

- pkg/client/live/client.go
This change handles an EOF condition more gracefully in the `live.Stream()` function by logging it with a lower verbosity level (V(4)) rather than treating it as a regular error (V(1)). 
Instead of:
`klog.V(1).Infof("r.Read failed. Err: %v\n", err)`
It logs:
`klog.V(4).Infof("r.Read encountered EOF. Err: %v\n", err)`
> EOF error logging with lower verbosity level

- examples/streaming/microphone/main.go
- pkg/api/version/analyze-version.go
- pkg/api/version/constants.go
- pkg/api/version/live-version.go
- pkg/api/version/manage-version.go
- pkg/api/version/prerecorded-version.go
- pkg/client/interfaces/utils.go
This supports overriding the protocol for REST and Websocket connections.
All examples work correctly!
NA
> Support Overriding Protocol for On-Prem

- examples/prerecorded/file/main.go
- examples/prerecorded/intent/main.go
- examples/prerecorded/sentiment/main.go
- examples/prerecorded/stream/main.go
- examples/prerecorded/summary/main.go
- examples/prerecorded/topic/main.go
- examples/streaming/microphone/main.go
- pkg/api/version/prerecorded-version.go
- pkg/client/live/client.go
- pkg/client/live/types.go
- pkg/client/prerecorded/client.go
- pkg/client/prerecorded/types.go
- pkg/client/rest/http.go
- pkg/client/rest/rest.go
- pkg/client/rest/types.go
- tests/prerecorded_test.go
Fixes copy and paste oops when implementing the On-Prem host parameter. Accidentally copied and pasted from live client which is wss/ws.
Adding some logging to help troubleshoot and reset the examples log levels back to normal.
> Fix On-Prem Host for Prerecorded, Add More Debug Trace

- examples/streaming/microphone/main.go
- pkg/api/live/v1/default.go
- pkg/api/live/v1/interfaces/constants.go
- pkg/api/live/v1/interfaces/interfaces.go
- pkg/api/live/v1/interfaces/types.go
- pkg/api/live/v1/router.go
- pkg/client/interfaces/types-stream.go
This implements `vad_events` in order to trigger speech started events.
The `examples/streaming/microphone` example has been updated to test the functionality.
NA
> Implements `vad_events` for SpeechStarted

- pkg/api/live/v1/interfaces/types.go
- pkg/api/prerecorded/v1/interfaces/types.go
The feature Extra had not been added to prerecorded or live `v1/interfaces/types` so I added it as the type `map[string]interface{}`. The user can add it as a string like this:
```go
options := interfaces.LiveTranscriptionOptions{
Extra:      "test:one",
}
```
> adds extra feature to metadata types

- pkg/client/analyze/client.go
Dereferences the pointer before passing it to the function, like this: `rest.New(*options)`
- [ x] Bugfix (non-breaking change which fixes an issue)
> fix: type mismatch in client options

- examples/streaming/test/main.go
- pkg/api/analyze/v1/interfaces/types.go
- pkg/api/live/v1/interfaces/types.go
- pkg/api/prerecorded/v1/interfaces/types.go
Addresses https://github.com/deepgram/deepgram-go-sdk/issues/163
For all parameters we don't want to include when null, use a pointer for JSON parsing. Tested using the examples.
NOTE: Combining just in the interest of time. Also fixes an issue with `Paragraph` -> `Paragraphs`: https://github.com/deepgram/deepgram-go-sdk/pull/174/files#diff-6d6a17cac219ff3f71886cf5d9bc5b4803f75690ab397ba1f72863920080d191R96
NA
> Remove Null Fields from Response Objects

- examples/streaming/http/main.go
- examples/streaming/microphone/main.go
- pkg/api/live/v1/default.go
- pkg/api/live/v1/interfaces/constants.go
- pkg/api/live/v1/interfaces/interfaces.go
- pkg/api/live/v1/interfaces/types.go
- pkg/api/live/v1/router.go
- pkg/client/live/client.go
Implements Open/Close events along with a Raw Unhandled event message when you have access to raw bytes. This could be useful for wanting to handle messages that aren't implemented yet.
Updated all examples to make use of the Open/Close event. The Unhandled event wont trigger until we have a new event that is introduced that this SDK doesn't handle (ie you should not see this event at all).
NA
> Implement Open/Close Event

- pkg/client/live/client.go
This PR fixes error handling inside `func (c *Client) Stream(r io.Reader) error` function.
The current implementation tries to call `err.Error()` in the first switch `case strings.Contains(err.Error(), FatalReadSocketErr)`.
It leads to a panic in case of handling successful results.
```
[Open] Received
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d94e3]
goroutine 353 [running]:
github.com/deepgram/deepgram-go-sdk/pkg/client/live.(*Client).Stream(0xc000400600, {0xf879a0, 0xc0007b6180})
.../go/pkg/mod/github.com/deepgram/deepgram-go-sdk@v1.3.0/pkg/client/live/client.go:356 +0x103
```
_Put an …
> Properly handle success result for live stream

- pkg/client/common/common.go
- pkg/client/live/client.go
This fixes a threading issue when writing from multiple sources after the refactor. The easy way to reproduce this was to enable KeepAlives.
NA
> Fix Write From Multi-Source (KeepAlive, etc)

- pkg/client/live/client.go
- pkg/client/live/constants.go
- tests/edge_cases/reconnect_client/main.go
This is hopefully the last fix for the reconnect logic. We found a couple of things that were preventing the reconnect. Most importantly, we ditched the attempt to reuse the context object. It just flat out wasn't working well. Because we now need to provide a context object on reconnect, it breaks the interface for the live client, but thankful the impact should only be in one place in the user's code.
Have a couple of examples to demonstrate client reuse and misc functionality (please also see https://github.com/deepgram/deepgram-go-sdk/pull/231).
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
> Fix Reconnect Logic

- pkg/client/live/client.go
- tests/edge_cases/cancel/main.go
This fixes an issue with the last PR https://github.com/deepgram/deepgram-go-sdk/pull/232 which even OpenResponse didn't have a corresponding CloseResponse.
This also fixes:
- an outstanding issue where the listen thread would take a while to disconnect after the socket was gone
- fires ErrorResponses for Deepgram, Fatal, etc type error messages
NA
> Fix Open/Close Event Pairing After Fatal Reconnect Refactor

- examples/streaming/http/main.go
- examples/streaming/microphone/main.go
- examples/streaming/replay/main.go
- examples/streaming/test/main.go
- pkg/client/live/client.go
- tests/edge_cases/cancel/main.go
- tests/edge_cases/failed_retry/main.go
- tests/edge_cases/keepalive/main.go
- tests/edge_cases/reconnect_client/main.go
- tests/edge_cases/timeout/main.go
Tested using all examples in `examples/streaming` and edges cases in `tests/edge_cases`.
This does break the main Connect function interfaces. Instead of returning the websocket connection, the function just returns true or false if the connect was successful or not.
NA
> Fix Repeated/Excessive Read Failure on WS

- examples/prerecorded/file/main.go
- examples/speak/stream/interactive/main.go
- examples/streaming/microphone/main.go
- pkg/api/live/v1/default.go
- pkg/api/live/v1/interfaces/types.go
- pkg/api/speak-stream/v1/interfaces/types.go
- pkg/client/interfaces/utils.go
- pkg/client/live/client.go
- pkg/client/live/constants.go
- pkg/client/speak/client_stream.go
- pkg/client/speak/constants.go
- tests/edge_cases/reconnect_client/main.go
This ports fixes from the STT WebSocket to the TTS WebSocket client. Please see for more details:
https://github.com/deepgram/deepgram-go-sdk/pull/243
https://github.com/deepgram/deepgram-go-sdk/pull/245
This also ports fixes made in TTS WebSocket -> STT WebSocket client made in this PR:
https://github.com/deepgram/deepgram-go-sdk/pull/239
Some other notes on changes:
- I removed the directory creation on `tts-output` since the `mp3` file is getting overwritten on subsequent streams.
- updated stream micro example to use updated error response struct
- fixed `examples/prerecorded/file` to fix the VTT and SRT
Tested STT and TTS examples!
_Put an `x` in the boxes that apply. You can …
> Port WebSocket Threading Fixes `STT Live` -> `TTS Speak`, Port Fixes From `TTS Speak` -> `STT Live`
